alias v='vim'
alias gs='git status'
alias gsu='git status -uno'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log'
alias gl='git log --oneline --decorate'
alias gb='git branch --sort=-committerdate'
alias gm='git merge'
alias gp='git pull'
alias gpush='git push'
alias git-rollback='git reset --soft HEAD~1'
alias git-undo-commit='git reset --hard HEAD~1'
alias git-init="git init && git add *  && git commit -m 'initial'"
alias git-clean='git clean -xfd'
alias git-delta='git diff --name-only'
alias git-new-branch='git checkout -b'
alias git-tree='git log --graph --pretty=oneline --abbrev-commit --decorate'
alias git-graph='git log --graph --pretty=oneline --abbrev-commit --decorate'
# Check=if HEAD is ff-mergable (prints 0 if it is):
alias git-ff='git merge-base --is-ancestor origin/fp_dev_execution HEAD && echo "$?"'
